### ISSUE TITLE
Error on running very basic Ping command 

### ISSUE THREAD

**Issue by jamiabailey** [ValentinBELYN/icmplib#81]
Just using the basic ping example posted here: https://pypi.org/project/icmplib/

I get the error "ping() got an unexpected keyword argument 'count'"

I am running Python version 3.9 within Visual Studio Community within a Flask App.

The exact code that will not function:
hostname = "8.8.8.8"
host = ping('8.8.8.8', count=10, interval=0.2)
if host.is_alive == True:
  color = "green"
  pingresult = hostname + " is up"
else:
  color = "red"
  pingresult = hostname + " is down"

Not sure what the deal is. Documentation states it should work with Python 3.7+ and the app I am testing with is very very basic use of this. Multiping works fine.

**Comment by ValentinBELYN** [comment]
Hi,

The `count` parameter of the `ping` function has existed since the very first version of the library. It is therefore not normal that this does not work.

Can you check that you have not declared a `ping` function in your code or that you have not imported a `ping` function from another library?

Furthermore, can you run the following code and send me the result:
```python3
import pydoc
print(pydoc.render_doc(ping))
```
